name: test_wav2vec2
type: wav2vec2
pretrained_model_id: chcaa/xls-r-300m-danish
freeze_feature_encoder: true

# Data hyperparameters
clean_dataset: true
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789é|'

# Model hyperparameters
sampling_rate: 16_000
activation_dropout: 0.1
attention_dropout: 0.1
hidden_dropout: 0.1
feat_proj_dropout: 0.1
final_dropout: 0.1
mask_time_prob: 0.075
mask_time_length: 10
mask_feature_prob: 0.075
mask_feature_length: 10
layerdrop: 0.1
ctc_loss_reduction: sum

# Decoder hyperparameters
language_model_decoder: null

# Training hyperparameters
batch_size: 1
gradient_accumulation: 1
max_steps: 3
learning_rate: 4e-5
warmup_steps: 1
early_stopping: true
early_stopping_patience: 5
fp16: false
