name: test-whisper
type: whisper
pretrained_model_id: openai/whisper-tiny
freeze_feature_encoder: true

# Data hyperparameters
lower_case: false
clean_text: false

# Model hyperparameters
sampling_rate: 16_000
dropout: 0.1
activation_dropout: 0.1
attention_dropout: 0.1
mask_time_prob: 0.5
mask_time_length: 10
mask_feature_prob: 0.5
mask_feature_length: 64
generation_max_length: 128
