name: test_wav2vec2
type: wav2vec2
pretrained_model_id: chcaa/xls-r-300m-danish
freeze_feature_encoder: true

# Data hyperparameters
clean_dataset: true

# Model hyperparameters
sampling_rate: 16_000
activation_dropout: 0.1
attention_dropout: 0.1
hidden_dropout: 0.1
feat_proj_dropout: 0.1
final_dropout: 0.1
mask_time_prob: 0.075
mask_time_length: 10
mask_feature_prob: 0.075
mask_feature_length: 10
layerdrop: 0.0  # NOTE: This parameter cannot be used in a multi-gpu setting!
ctc_loss_reduction: sum

# Decoder hyperparameters
language_model_decoder: null
