name: whisper-medium
type: whisper
pretrained_model_id: openai/whisper-medium
freeze_feature_encoder: false

# Data hyperparameters
lower_case: false

# Model hyperparameters
sampling_rate: 16_000
dropout: 0.0
activation_dropout: 0.0
attention_dropout: 0.0
mask_time_prob: 0.3
mask_time_length: 10
mask_feature_prob: 0.3
mask_feature_length: 64
generation_max_length: 128
