coral2-read:
  id: CoRal-dataset/coral-v2
  subset: read_aloud
  train_name: train
  text_column: text
  audio_column: audio
  filter_dataset: false
  eval_split_name: test
  eval_categories:
    age:
      (0,25): "0-25"
      (26,50): "25-50"
      (50,None): "50+"
    gender:
      male: Male
      female: Female
      nonbinary: Non-binary
    dialect:
      midtøstjysk: Østjysk
      østjysk: Østjysk
      københavnsk: Københavnsk
      amagermål: Københavnsk
      nørrejysk: Nordjysk
      vestjysk: Vestjysk
      nordsjællandsk: Sjællandsk
      sjællandsk: Sjællandsk
      fynsk: Fynsk
      bornholmsk: Bornholmsk
      sønderjysk: Sønderjysk
      vendsysselsk (m. hanherred og læsø): Nordjysk
      østligt sønderjysk (m. als): Sønderjysk
      nordvestsjællandsk: Sjællandsk
      thybomål: Vestjysk
      himmerlandsk: Nordjysk
      djurslandsk (nord-, syddjurs m. nord- og sydsamsø, anholt): Østjysk
      sydsjællandsk (sydligt sydsjællandsk): Sjællandsk
      sydfynsk: Fynsk
      morsingmål: Vestjysk
      sydøstjysk: Østjysk
      østsjællandsk: Sjællandsk
      "syd for rigsgrænsen: mellemslesvisk, angelmål, fjoldemål": Sønderjysk
      vestfynsk (nordvest-, sydvestfynsk): Fynsk
      vestlig sønderjysk (m. mandø og rømø): Sønderjysk
      sydvestjysk (m. fanø): Vestjysk
      sallingmål: Vestjysk
      nordfalstersk: Sydømål
      langelandsk: Fynsk
      sydvestsjællandsk: Sjællandsk
      lollandsk: Sydømål
      sydømål: Sydømål
      ommersysselsk: Østjysk
      sydfalstersk: Sydømål
      fjandbomål: Vestjysk



