defaults:
  - model: wav2vec2-with-lm
  - datasets:
    - common_voice_13_da
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models
  hidden: hidden

seed: 4242

evaluation_dataset:
  id: CoRal-dataset/coral_v1.0
  subset: null
  split: test
  val_name: validation
  test_name: test
  text_column: text
  audio_column: filename

# Dataset parameters
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789éü'
max_seconds_per_example: 10
dataloader_num_workers: 4

# Can be `longest`, `max_length` or `do_not_pad`
# NOTE: This is automatically set to `max_length` in a multi-gpu setting
padding: longest

# This is a list of the sampling probability of each dataset, where null means that
# each dataset will be sampled equally often
dataset_probabilities: null

# Model parameters
model_id: ${model.name}-${now:%Y-%m-%d}
model_dir: ${dirs.models}/${model_id}
hub_organisation: alexandrainst
push_to_hub: false
fp16: true

# Training parameters
wandb: false
wandb_project: CoRal
wandb_group: default
wandb_name: ${model_id}
resume_from_checkpoint: false
ignore_data_skip: false
save_total_limit: 2

# Optimisation parameters
learning_rate: 1e-4
adam_first_momentum: 0.9
adam_second_momentum: 0.98
total_batch_size: 256
per_device_batch_size: 16
max_steps: 10_000
warmup_steps: 1_000
logging_steps: 10
eval_steps: 100
save_steps: 100
early_stopping: false
early_stopping_patience: 50

dataset_creation:
  num_split_attempts: 1000
  mean_seconds_per_sample: 5.0
  genders:
    - female
    - male
  dialects:
    - Bornholmsk
    - Fynsk
    - Københavnsk
    - Nordjysk
    - Sjællandsk
    - Sydømål
    - Sønderjysk
    - Vestjysk
    - Østjysk
  age_groups:
    - min: 0
      max: 25
    - min: 25
      max: 50
    - min: 50
      max: null
  accents:
    - native
    - foreign
  sub_dialect_to_dialect:
    midtøstjysk: Østjysk
    østjysk: Østjysk
    amagermål: Københavnsk
    nørrejysk: Nordjysk
    vestjysk: Vestjysk
    nordsjællandsk: Sjællandsk
    sjællandsk: Sjællandsk
    fynsk: Fynsk
    bornholmsk: Bornholmsk
    sønderjysk: Sønderjysk
    vendsysselsk (m. hanherred og læsø): Nordjysk
    østligt sønderjysk (m. als): Sønderjysk
    nordvestsjællandsk: Sjællandsk
    thybomål: Vestjysk
    himmerlandsk: Nordjysk
    djurslandsk (nord-, syddjurs m. nord- og sydsamsø, anholt): Østjysk
    sydsjællandsk (sydligt sydsjællandsk): Sjællandsk
    sydfynsk: Fynsk
    morsingmål: Vestjysk
    sydøstjysk: Østjysk
    østsjællandsk: Sjællandsk
    syd for rigsgrænsen: mellemslesvisk, angelmål, fjoldemål: Sønderjysk
    vestfynsk (nordvest-, sydvestfynsk): Fynsk
    vestlig sønderjysk (m. mandø og rømø): Sønderjysk
    sydvestjysk (m. fanø): Vestjysk
    sallingmål: Vestjysk
    nordfalstersk: Sydømål
    langelandsk: Fynsk
    sydvestsjællandsk: Sjællandsk
    lollandsk: Sydømål
    sydømål: Sydømål
    ommersysselsk: Østjysk
    sydfalstersk: Sydømål
    fjandbomål: Vestjysk
  requirements:
    test:
      min_hours: 7.5
      max_hours: 20.0
      gender_pct: 0.4
      dialect_pct: 0.1
      age_group_pct: 0.2
      accent_pct: 0.05
    val:
      min_hours: 1.0
      max_hours: 10.0
      gender_pct: 0.2
      dialect_pct: 0.01
      age_group_pct: 0.1
      accent_pct: 0.01
