defaults:
  - model: wav2vec2_alvenir_config
  - datasets:
    - nst_da
    - common_voice_9_da
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

seed: 4242

# Dataset parameters
dataset_probabilities:  # null = equal probability to every dataset
  train: null
  val: null
  test: null

# Model parameters
pipeline_id: ${model.name}-finetuned
hub_id: alexandrainst/${pipeline_id}
model_dir: ${dirs.models}/${pipeline_id}
push_to_hub: false

# Training parameters
wandb: false
wandb_project: CoRal
wandb_group: default
wandb_name: null
resume_from_checkpoint: false
ignore_data_skip: false
logging_steps: 10
eval_steps: 100
save_steps: 100
save_total_limit: 2
early_stopping: false
early_stopping_patience: 50
fp16: true
