defaults:
  - model: wav2vec2
  - dataset: common_voice_da
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

seed: 4242

# Model parameters
pipeline_id: ${model.name}-${dataset.name}
hub_id: alexandrainst/${pipeline_id}
model_dir: ${dirs.models}/${pipeline_id}
push_to_hub: false

# Training parameters
resume_from_checkpoint: false
ignore_data_skip: false
wandb: false
wandb_name: default
logging_steps: 100
eval_steps: 500
save_steps: 500
save_total_limit: 2
