model_id: openai/whisper-large-v3
dataset_id: alexandrainst/coral
dataset_subset: read_aloud
dataset_split: null
dataset_revision: null
text_column: text
audio_column: audio
output_dataset_id: alexandrainst/coral
output_dataset_subset: read_aloud
output_dataset_split: null
batch_size: 16
cache_dir: null
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789éü'
max_seconds_per_example: 10
sample_rate: 16_000
metrics:
  - name: wer
    max: 1.0
  - name: cer
    max: 1.0
