model_id: alexandrainst/coral-asr-bootstrap
dataset_id: alexandrainst/coral
dataset_subset: read_aloud
dataset_split: null
dataset_revision: null
text_column: text
audio_column: audio
output_dataset_id: alexandrainst/coral
output_dataset_subset: read_aloud
output_dataset_split: null
batch_size: 8
cache_dir: null
