model_id: openai/whisper-large-v3
dataset_id: alexandrainst/coral
dataset_subset: read_aloud
dataset_split: null
dataset_revision: null
text_column: text
audio_column: audio
output_dataset_id: alexandrainst/coral
output_dataset_subset: read_aloud
output_dataset_split: null
batch_size: 8
cache_dir: null
max_train_wer: 1.0
max_val_test_wer: 0.4
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789éü'
metrics:
  - wer
  - cer
