# ASR model parameters
model_id: Alvenir/coral-1-whisper-large
model_type: whisper
sampling_rate: 16_000

# UI parameters
title: Velkommen til RØST - hele Danmarks talegenkendelsesmodel
description: >
  [RØST](https://huggingface.co/Alvenir/coral-1-whisper-large) er en talegenkendelsesmodel udviklet som en del af Grand Solution projektet: [CoRal](https://alexandra.dk/coral/). RØST er designet til at fremme dansk taleteknologi ved at tilbyde en åben og transparent model, der er tilgængelig for alle og kan anvendes til en bred vifte af formål.


  I CoRal-projektet er der indsamlet et omfattende datasæt med danske taledata, som kan bruges til at forbedre talegenkendelsesteknologier på dansk. Datasættet indeholder både oplæst tale og samtaledata fra et bredt og repræsentativt udsnit af den danske befolkning - inklusive dialekter og accenter. Dette danner grundlaget for udvikling af talegenkendelsesmodeller, der kan bruges af hele den danske befolkning og give adgang kunstig intelligens i stor skala.


  Sådan burger du CoRal:
  <ol>
    <li>Tryk på "Record" og tal ind i mikrofonen</li>
    <li>Tryk på "Stop", når du er færdig</li>
    <li>Tryk på "Submit" og få dine ord transskriberet</li>
  </ol>


  Du kan også uploade en lydfil ved at trykke på <img src="https://cdn-icons-png.flaticon.com/128/3097/3097412.png" width="14px" style="vertical-align: middle; display: inline;"> knappen.
