# ASR model parameters
model_id: Alvenir/coral-1-whisper-large
model_type: whisper
sampling_rate: 16_000

# UI parameters
title: Hørt Speech-to-Text Demo
description: >
  This is a demo of the Danish speech recognition model:
  [Hørt](https://huggingface.co/Alvenir/coral-1-whisper-large).


  Press "Record" to record your own voice. When you're done you can press "Stop" to stop
  recording and "Submit" to send the audio to the model for transcription. You can also
  upload an audio file by pressing the <img src="https://cdn-icons-png.flaticon.com/128/3097/3097412.png" width="14px" style="vertical-align: middle; display: inline;"> button.

# Web server options
server_name: 0.0.0.0
server_port: 7860
