defaults:
  - datasets:
    - coral
    - common_voice_17
    - fleurs
    - nst

cache_dir: ".coral-cache"

subset_size: null #null if using all of data

# Filtering of the dataset
min_seconds_per_example: 0.5
max_seconds_per_example: 10

# Processing of the dataset
clean_text: true
lower_case: true
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789éü'
normalize_audio: false

# Evaluation parameters
model_id: null
no_lm: false  # This is only relevant for Wav2Vec 2.0 models
sampling_rate: 16_000
metrics:
  - cer
  - wer
batch_size: 16
bootstrap_samples: 1000
store_results: true
detailed: true