# Evaluation dataset parameters
dataset_id: alexandrainst/coral
dataset_subset: read_aloud
dataset_revision: null
val_name: val
test_name: test
text_column: text
audio_column: audio

# Filtering of the dataset
filter_dataset: true
min_seconds_per_example: 0.5
max_seconds_per_example: 10

# Processing of the dataset
process_dataset: true
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789éü'

# Evaluation parameters
model_id: null
batch_size: 16
