# Evaluation dataset parameters
dataset_subset: read_aloud
dataset_revision: null
eval_split_name: test
cache_dir: null

# Filtering of the dataset
do_filter_dataset: true
min_seconds_per_example: 0.5
max_seconds_per_example: 10

# Processing of the dataset
do_process_dataset: true
characters_to_keep: 'abcdefghijklmnopqrstuvwxyzæøå0123456789éü'

# Evaluation parameters
model_id: null
sampling_rate: 16_000
metric: cer
batch_size: 16
