streaming: true
num_split_attempts: 1000
mean_seconds_per_sample: 5.0

genders:
  - female
  - male

dialects:
  - Bornholmsk
  - Fynsk
  - Københavnsk
  - Nordjysk
  - Sjællandsk
  - Sydømål
  - Sønderjysk
  - Vestjysk
  - Østjysk

age_groups:
  - [0, 25]
  - [25, 50]
  - [50, null]

accents:
  - native
  - foreign

sub_dialect_to_dialect:
  midtøstjysk: Østjysk
  østjysk: Østjysk
  amagermål: Københavnsk
  nørrejysk: Nordjysk
  vestjysk: Vestjysk
  nordsjællandsk: Sjællandsk
  sjællandsk: Sjællandsk
  fynsk: Fynsk
  bornholmsk: Bornholmsk
  sønderjysk: Sønderjysk
  vendsysselsk (m. hanherred og læsø): Nordjysk
  østligt sønderjysk (m. als): Sønderjysk
  nordvestsjællandsk: Sjællandsk
  thybomål: Vestjysk
  himmerlandsk: Nordjysk
  djurslandsk (nord-, syddjurs m. nord- og sydsamsø, anholt): Østjysk
  sydsjællandsk (sydligt sydsjællandsk): Sjællandsk
  sydfynsk: Fynsk
  morsingmål: Vestjysk
  sydøstjysk: Østjysk
  østsjællandsk: Sjællandsk
  "syd for rigsgrænsen: mellemslesvisk, angelmål, fjoldemål": Sønderjysk
  vestfynsk (nordvest-, sydvestfynsk): Fynsk
  vestlig sønderjysk (m. mandø og rømø): Sønderjysk
  sydvestjysk (m. fanø): Vestjysk
  sallingmål: Vestjysk
  nordfalstersk: Sydømål
  langelandsk: Fynsk
  sydvestsjællandsk: Sjællandsk
  lollandsk: Sydømål
  sydømål: Sydømål
  ommersysselsk: Østjysk
  sydfalstersk: Sydømål
  fjandbomål: Vestjysk

requirements:
  max_val_test_wer: 0.4
  test:
    min_hours: 7.5
    max_hours: 20.0
    gender_pct: 0.4
    dialect_pct: 0.1
    age_group_pct: 0.2
    accent_pct: 0.05
  val:
    min_hours: 1.0
    max_hours: 10.0
    gender_pct: 0.4
    dialect_pct: 0.05
    age_group_pct: 0.1
    accent_pct: 0.05
