version: 1
formatters:
  simple:
    format: "%(asctime)s ⋅ %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    level: info
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  handlers: [console]

disable_existing_loggers: false
