version: 1
formatters:
  simple:
    format: "%(asctime)s ⋅ %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    level: info
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
root:
  handlers: [console, file]

disable_existing_loggers: false
